### ISSUE TITLE
No Unity 2020.2.4 in Docker Hub

### ISSUE THREAD

**Issue by uchar** [game-ci/docker#79] opened 2021-02-15 10:46 UTC
Unity 2020.2.4 is out for some days now, But I can't find it in Docker Hub. Not sure how those images generated but maybe something failed?

**Comment by GabLeRoux** [comment] 2021-02-15 13:41
Jst had a similar discussion on discord;

> Hi, guys! Is there any way to force build images for Unity 2020.2.4 ?? Would like to switch to this version of the editor in my project

We have some failed jobs for previous versions which are blocking new versions right now. We will have a look at it tonight.


> Out of curiosity, usually how fast new versions get uploaded as docker images?


Sometimes it is even published before unity creates a release post for it. We crawl their website and enqueue jobs as soon as a new version is detected every 15 minutes.
But lately we had some troubles building some of the previous versions with v0.9 so after several retries, the jobs are stopped to give us some time to fix the repository and prevent releasing new possibly broken images.

I'll try to fix this tonight.

**Comment by L4ZZA** [comment] 2021-02-22 11:03
Any news on this? We have also just updated to 2020.2.x and now our CI is blocked as we can't update the docker image on which our build step is running :(

**Comment by webbertakken** [comment] 2021-02-22 11:54
I'm currently working on an interface that allows us to debug builds that are stuck. The overview [part](https://github.com/game-ci/documentation/pull/100) of our images is already in. The button-to-be to unstuck specific builds requires further development.

Please allow a few more days to further develop the debugging feature (so we don't have to unstuck builds manually every time). In the meantime there are 2020.2.x images [available](https://game.ci/docs/docker/versions), just not the latest one yet.

**Comment by basdp** [comment] 2021-02-28 19:33
Just a quick suggestion, as we have multiple issues being reported for the different missing versions; can we have a central ticket to track the overarching problem and the fix for that? That must prevent new tickets from popping up for other versions and that way we communicate better that the issue is worked on.

**Comment by webbertakken** [comment] 2021-02-28 19:45
It's a good suggestion, but at the same time it will only create more noise. We expect to be fixing them a lot faster in the future either way.

We created an overview page that can be found [here](http://localhost:3000/docs/docker/versions)

I talked about manually debugging workflows that are stuck. We have build some functionality on top of mentioned overview, that allows admins to restart builds. It's in review at the time of writing.

Frontend part: https://github.com/game-ci/documentation/pull/110
Backend part: https://github.com/game-ci/versioning-backend/pull/31

As for the [build](https://github.com/game-ci/docker/actions/runs/608278832) that is stuck currently. It needs a fix.

**Comment by webbertakken** [comment] 2021-02-28 22:20
It's [running](http://localhost:3000/docs/docker/versions).

![image](https://user-images.githubusercontent.com/20756439/109435566-5e50ee80-7a1b-11eb-834f-1e5ade14b433.png)

Closing this issue. Thanks for bringing it up!

**Closed by webbertakken** 2021-02-28 22:20 UTC
Labels: bug
