### ISSUE TITLE
Unity 2022.2 Android JDK not found

### ISSUE THREAD

**Issue by joaoborks** [game-ci/docker#202] opened 2023-02-14 18:12 UTC
**Bug description**

I'm unable to build my game for android due to this error:

```
DisplayProgressbar: Detect Java Development Kit (JDK)
UnityException: JDK not found
Java Development Kit (JDK) directory is not set or invalid. Please, fix it in Edit / Unity -> Preferences -> External Tools
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck(String[], String, String, BuildTargetGroup, BuildTarget, Int32, BuildOptions, String[], Boolean)
UnityEditor.BuildPipeline:BuildPlayerInternal(String[], String, String, BuildTargetGroup, BuildTarget, Int32, BuildOptions, String[]) (at /home/bokken/build/output/unity/unity/Editor/Mono/BuildPipeline.bindings.cs:481)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, String, BuildTargetGroup, BuildTarget, Int32, BuildOptions, String[]) (at /home/bokken/build/output/unity/unity/Editor/Mono/BuildPipeline.bindings.cs:359)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions) (at /home/bokken/build/output/unity/unity/Editor/Mono/BuildPipeline.bindings.cs:323)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions) (at /home/bokken/build/output/unity/unity/Editor/Mono/BuildPipeline.bindings.cs:318)
BuildCommand:PerformBuild() (at Assets/_Project/Scripts/Editor/BuildCommand.cs:227)
(Filename: Assets/_Project/Scripts/Editor/BuildCommand.cs Line: 227)
```

We're using the [unityci/editor:2022.2.5f1-android-1](https://hub.docker.com/layers/unityci/editor/2022.2.5f1-android-1/images/sha256-2767005124ae0bcc68c2b481f548577c548d504bfb0eb378a78005270f2a22e2) image.

**How to reproduce**

- Use the [unityci/editor:2022.2.5f1-android-1](https://hub.docker.com/layers/unityci/editor/2022.2.5f1-android-1/images/sha256-2767005124ae0bcc68c2b481f548577c548d504bfb0eb378a78005270f2a22e2) image to build a game for Android.

**Expected behavior**

The build pipeline is able to locate and correctly setup the JDK, and successfully builds the application. Example log from the [unityci/editor:2021.3.9f1-android-1](https://hub.docker.com/layers/unityci/editor/2021.3.9f1-android-1/images/sha256-18f3254559f44b0486398602efae1b07092196ec7c69253e35d3909650abe36d) image:

```
DisplayProgressbar: Detect Java Development Kit (JDK)
Android PostProcess task "Detect Java Development Kit (JDK)" took 313.5795 ms
```

**Additional details**

The 2022.2.0 update introduced a few breaking changes for Android:

* Android: Android SDK must have cmdline-tools component installed now. Unity will ignore tools component.
* Android: Default gradle templates have changed significantly with new Gradle and AGP versions. Gradle templates in existing projects will have to be recreated based on new default templates when upgrading projects created with previous Unity versions.
* Android: Implemented a new system to generate Android manifests internally.
* **Android: JDK 11 is now required to build Android apps.**
* Android: Removed Editor UI option that previously allowed you to choose between R8 and Proguard tools to minify code. The new AGP version doesn't have an option to minify using proguard, so R8 is always used instead.
* Android: Unity uses Android Gradle Plugin 7.1.2 by default.
* Android: Unity uses Gradle 7.2 by default.
* Android: Upgraded to using Android NDK r23b. Default linker is now lld which fixes issues with large projects and IL2CPP.
_[From the official 2022.2.0 changelog](https://unity.com/releases/editor/whats-new/2022.2.0#Changes:~:text=in%20package%20manager.-,Changes,-2D%3A%20Added%20support)_

I guess that the JDK 11 bump broke something in the CI image.

**Comment by davidmfinol** [comment] 2023-02-14 18:26
This is a duplicate of https://github.com/game-ci/unity-builder/issues/489

**Closed** 2023-05-07 15:34 UTC
Labels: bug, duplicate
