### ISSUE TITLE
Able to override machine id

### ISSUE THREAD

**Issue by lsjostro** [game-ci/docker#49] opened 2020-11-17 08:01 UTC
**Bug description**

It would have been nice to be able to override the machine id? Maybe use `ENV MACHINE_ID` with the current default value?
https://github.com/Unity-CI/docker/blob/main/base/Dockerfile#L37

Thanks for the great work btw! 🚀

**Comment by webbertakken** [comment] 2020-11-17 08:20
Could you please elaborate as to why you would want that?

Kindly use the the prescribed format to prevent non actionable issues in the future. This is also not a bug.

**Comment by lsjostro** [comment] 2020-11-17 09:15
It's not a blocker or anything just that it might look "funny" on the Unity side having tons of license issuing on the same machine id for all users of this container don't you think? 

Sorry for the bug report. you're totally right is more of an enhancement. 😊

**Comment by webbertakken** [comment] 2020-11-17 09:43
We've had this discussion before on discord, but couldn't come up with any objective reason to make it configurable.

**Comment by GabLeRoux** [comment] 2020-11-17 09:52
On the other hand, we also thought about what if Unity would decide to somehow block activation for the machine id we hardcoded. It would probably require us to republish all of the images. Luckily for us, it's now much easier than before to publish new versions 🎉 .

An other use case I could see would be to ease migration process from `gableroux/unity3d` images to the new ones by allowing a _different path_. Example: Instead of having to activate again, you can extract the value of an existing previous image and reuse the same license as before. This could allow more _reproductible builds_ to ease compatibility comparisons. Other example: trying older image and new image in a same pipeline with same license.

I do like the idea.

**Comment by webbertakken** [comment] 2020-11-17 10:01
Indeed.

> This could allow more reproductible builds to ease compatibility comparisons.

But this just moves the responsibility away from a Pull Request into hardware id. In my opinion you shouldn't merge a PR that migrates to the new images if you haven't activated for the new hardware id.

> Other example: trying older image (`gableroux/unity3d`) and new image (`unity-ci/editor`) in a same pipeline with same license.

This would be a legitimate case. But I still feel it's a bit thin (especially if that's the only reason).

In my opinion we still shouldn't do it because we'll have to maintain the feature (which is very fundamental) and also support people that are customising it. There will for sure be people that customise it because they think it's "easier" that way. While in fact it'll be more confusing for people that don't have this context.

**Comment by GabLeRoux** [comment] 2020-11-17 10:32
Can this be configured at the end of build? If so, we could simply document how to do it. Example"

```dockerfile
FROM unityci/editor:2018.2.14f1-ios-0.6.0

# then override machine id here
```

**Comment by webbertakken** [comment] 2020-11-17 12:07
Yes, that is possible, I think documenting this would be better than natively offering support for this indeed. I really like that idea!

**Comment by webbertakken** [comment] 2021-03-01 22:31
Closing this as it's not currently an issue. Documenting this might be a bit overkill. Feel free to comment if new relevant information comes to light.

**Closed by webbertakken** 2021-03-01 22:31 UTC
Labels: enhancement, good first issue
