### ISSUE TITLE
Roslyn csc exits with Segmentation fault

### ISSUE THREAD

**Issue by brandesign** [game-ci/docker#86] opened 2021-02-24 09:37 UTC
Hello,
I am setting up a testing pipeline on gitlab and always get a segfault when running the tests:
` -----CompilerOutput:-stdout--exitcode: 139--compilationhadfailure: True--outfile: Temp/UnityEngine.TestRunner.dll
 -----CompilerOutput:-stderr----------
 /opt/unity/Editor/Data/Tools/RoslynScripts/unity_csc.sh: line 13:   467 Segmentation fault      (core dumped) "/opt/unity/Editor/Data/Tools/RoslynScripts/../../Tools/Roslyn/csc" /shared /noconfig @Temp/UnityTempFile-f986ab8ffbc50a42cb29d29ed01f73ca
 -----EndCompilerOutput---------------`
I added `export RoslynCommandLineLogFile=$UNITY_DIR/roslyn.log` to my script and get no useful hints :( Has anyone an idea what could be causing this? Could it be, that the gitlab runners resources are too low?

> --- PID=469 TID=1 Ticks=300302408: Attempt to open named pipe 'fk0ePXpgfzxwDCqHQp37sqgqEEy74tUh2YFuCiPy1CM'
> --- PID=469 TID=1 Ticks=300302410: Attempt to connect named pipe 'fk0ePXpgfzxwDCqHQp37sqgqEEy74tUh2YFuCiPy1CM'
> --- PID=499 TID=1 Ticks=300302656: Keep alive timeout is: 600000 milliseconds.
> --- PID=499 TID=1 Ticks=300302667: Constructing pipe 'fk0ePXpgfzxwDCqHQp37sqgqEEy74tUh2YFuCiPy1CM'.
> --- PID=499 TID=1 Ticks=300302722: Successfully constructed pipe 'fk0ePXpgfzxwDCqHQp37sqgqEEy74tUh2YFuCiPy1CM'.
> --- PID=499 TID=1 Ticks=300302722: Waiting for new connection
> --- PID=469 TID=5 Ticks=300302725: Named pipe 'fk0ePXpgfzxwDCqHQp37sqgqEEy74tUh2YFuCiPy1CM' connected
> --- PID=499 TID=1 Ticks=300302730: Pipe connection detected.
> --- PID=499 TID=1 Ticks=300302730: Memory available - accepting connection
> --- PID=469 TID=5 Ticks=300302732: Creating BuildRequest
> --- PID=469 TID=5 Ticks=300302732: Working directory: /builds/awsm-core/frontend
> --- PID=469 TID=5 Ticks=300302732: Temp directory: /tmp/
> --- PID=469 TID=5 Ticks=300302733: Lib directory: null
> --- PID=469 TID=5 Ticks=300302733: Compiler hash: 8da8ba0cf0754c14cff7fb7d22335889f7f44f2b
> --- PID=469 TID=5 Ticks=300302733: argument[0] = /noconfig
> --- PID=469 TID=5 Ticks=300302733: argument[1] = @Temp/UnityTempFile-48a82e7836b7181ad97aeb42ed582173
> --- PID=469 TID=5 Ticks=300302743: Begin writing request
> --- PID=499 TID=1 Ticks=300302744: Client 0: Begin reading request.
> --- PID=499 TID=1 Ticks=300302751: Reading length of request
> --- PID=469 TID=5 Ticks=300302751: Formatting request
> --- PID=469 TID=5 Ticks=300302754: Writing length of request.
> --- PID=499 TID=1 Ticks=300302755: Attempting to read 4 bytes from the stream
> --- PID=469 TID=5 Ticks=300302759: Writing request of size 325
> --- PID=469 TID=5 Ticks=300302761: End writing request
> --- PID=469 TID=5 Ticks=300302761: Begin reading response
> --- PID=469 TID=5 Ticks=300302764: Reading response length
> --- PID=469 TID=5 Ticks=300302771: Attempting to read 4 bytes from the stream
> --- PID=499 TID=1 Ticks=300302784: Read 4 bytes
> --- PID=499 TID=1 Ticks=300302784: Finished read
> --- PID=499 TID=1 Ticks=300302784: Attempting to read 325 bytes from the stream
> --- PID=499 TID=1 Ticks=300302785: Read 325 bytes
> --- PID=499 TID=1 Ticks=300302785: Finished read
> --- PID=499 TID=1 Ticks=300302785: Parsing request
> --- PID=499 TID=1 Ticks=300302790: Client 0: End reading request.
> --- PID=499 TID=7 Ticks=300302810: Client 0: Begin compilation
> --- PID=499 TID=1 Ticks=300302828: Constructing pipe 'fk0ePXpgfzxwDCqHQp37sqgqEEy74tUh2YFuCiPy1CM'.
> --- PID=499 TID=1 Ticks=300302829: Successfully constructed pipe 'fk0ePXpgfzxwDCqHQp37sqgqEEy74tUh2YFuCiPy1CM'.
> --- PID=499 TID=1 Ticks=300302829: Waiting for new connection
> --- PID=499 TID=7 Ticks=300302836: CurrentDirectory = '/builds/awsm-core/frontend'
> --- PID=499 TID=7 Ticks=300302836: LIB = ''
> --- PID=499 TID=7 Ticks=300302836: Argument[0] = '/noconfig'
> --- PID=499 TID=7 Ticks=300302836: Argument[1] = '@Temp/UnityTempFile-48a82e7836b7181ad97aeb42ed582173'
> --- PID=499 TID=7 Ticks=300303222: Begin Analyzer Consistency Check
> --- PID=499 TID=7 Ticks=300303231: End Analyzer Consistency Check
> --- PID=499 TID=7 Ticks=300303231: ****Running C# compiler...
> --- PID=499 TID=7 Ticks=300309843: ****C# Compilation complete.
> ****Return code: 0
> ****Output:
> Microsoft (R) Visual C# Compiler version 3.5.0-dev-20359-01 (8da8ba0c)
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> 
> 
> --- PID=499 TID=7 Ticks=300309843: Client 0: End compilation
> --- PID=499 TID=7 Ticks=300309844: Client 0: Begin writing response.
> --- PID=499 TID=7 Ticks=300309846: Formatting Response
> --- PID=499 TID=7 Ticks=300309846: Writing response length
> --- PID=499 TID=7 Ticks=300309848: Writing response of size 277
> --- PID=499 TID=7 Ticks=300309848: Client 0: End writing response.
> --- PID=469 TID=6 Ticks=300309851: Read 4 bytes
> --- PID=469 TID=6 Ticks=300309851: Finished read
> --- PID=499 TID=7 Ticks=300309851: Pipe 0: Closing.
> --- PID=469 TID=6 Ticks=300309852: Reading response of length 277
> --- PID=469 TID=6 Ticks=300309852: Attempting to read 277 bytes from the stream
> --- PID=469 TID=6 Ticks=300309852: Read 277 bytes
> --- PID=469 TID=6 Ticks=300309852: Finished read
> --- PID=469 TID=6 Ticks=300309854: End reading response

**Comment by brandesign** [comment] 2021-02-24 09:42
Sorry, I forgot to mention that we use Unity 2020.2.3.f1

**Comment by mob-sakai** [comment] 2021-03-03 04:32
Try the `-nographics` option.

If you're using the `game-ci/unity-test-runner` action, See https://github.com/game-ci/unity-test-runner/issues/95.

**Comment by cozyGalvinism** [comment] 2021-03-22 12:57
I'm having the same issue, version 2019.3.2f1. 
[I attached my job log](https://github.com/game-ci/docker/files/6182265/job.txt)

I used the example CI folder, so `-nographics` is set for us.

**Comment by webbertakken** [comment] 2021-04-02 12:42
> **EDIT2:** It was indeed caused by an error in the BuildCommand.cs

Could you please elaborate what the error was and whether there is something we could improve, so that others can learn from this issue in the future?

**Comment by cozyGalvinism** [comment] 2021-04-04 21:39
Sure thing.

Essentially, I partially overwrote my existing `BuildCommand.cs` with this new one and overwrote a function I was referencing. Since I didn't look at Unity (which had thrown an error message about it) but rather pushed it straight to CI, Unity began building up to the point of the function call, where it then segfaulted.

My guess is that Unity just doesn't check for compiler errors in the script file before executing it, leading to some strange effects.

So make sure your `BuildCommand.cs` contains no errors, if you roll with your own version (we essentially added support for asset bundle building and some more variables for our game)

**Comment by davidmfinol** [comment] 2021-08-04 06:16
Closing this issue as the root cause was a compiler error in the user's build method.

**Closed by davidmfinol** 2021-08-04 06:16 UTC
