### ISSUE TITLE
Manifest unknown for certain images on unityci/editor but not for others.

### ISSUE THREAD

**Issue by Tuntenfisch** [game-ci/docker#218] opened 2023-07-25 09:51 UTC
Hello,

I'm trying to set up Game.CI on my university's GitLab server and am currently using Unity 2022.3.3f1. But when the CI Pipeline is attempting to pull the image it is unable to do so:

![image](https://github.com/game-ci/docker/assets/11965324/68286bab-eee1-4093-a4ea-fd46bcc29d1c)

While trying to find the reason for the "unknown manifest" error, I attempted to pull several other (older) images such as [2021.2.8f1-base-1.0.0](https://hub.docker.com/layers/unityci/editor/2021.2.8f1-base-1.0.0/images/sha256-2f06ff2c91b46f8052ed5044f6e453e64d0e9404ff9878917e64f830ab1cb85e?context=explore) and those work fine. I'm currently looking for any pointers on what could be the issue here. 

Could it be network/firewall related?

**Comment by mikekhristo** [comment] 2023-09-12 01:09
Did you find a solution?

**Comment by webbertakken** [comment] 2023-09-12 08:35
This usually only happens when people are trying to pull an image that really hasn't been published yet.

You can see the list of published images here: https://game.ci/docs/docker/versions

Note that v1.1.2 is not the latest version and no longer publishes new images. To use v2.x.x make sure to upgrade your project to use the latest GitLab example or GitHub Action (builder, runner etc.)

Closing this is most likely not a bug (and if it is the lack of info to reproduce the issue).

**Closed by webbertakken** 2023-09-12 08:35 UTC
