### ISSUE TITLE
2022.1 Support

### ISSUE THREAD

**Issue by hughesjs** [game-ci/docker#129] opened 2021-11-09 21:34 UTC
Context

Trying to set this up for my personal project, using 2022.1. (It's [here](https://github.com/hughesjs/earth-sim/) if you want to see it for additional context).

I get this error:

manifest for unityci/editor:2022.1.0a13-linux-il2cpp-0 not found: manifest unknown: manifest unknown

Judging from #52, this is just an issue with not having the right docker image available

Suggested solution

Create docker container for this build scenario

**Additional details**

I did raise this here, but I think this is probably the best place so I've closed it there.
https://github.com/game-ci/unity-actions/issues/127

**Comment by davidmfinol** [comment] 2021-11-09 21:36
This is an alpha version of Unity version, and we don't yet support alpha or beta versions of Unity.
I'd say this is a duplicate of https://github.com/game-ci/docker/issues/50

**Comment by hughesjs** [comment] 2021-11-09 21:41
Ahh right okay, I wonder why there's a different way to build the images for prerelease versions

**Comment by hughesjs** [comment] 2021-11-09 21:47
I've downgraded to 2021.2.1f1 which has got me going for now

**Comment by webbertakken** [comment] 2021-11-09 21:48
> Ahh right okay, I wonder why there's a different way to build the images for prerelease versions

As mentioned https://github.com/game-ci/docker/issues/50#issuecomment-734372395, new versions occasionally break because of missing libraries. Oftentimes Unity fixes these issues before moving to stable for that version.

Closing as duplicate of #50.

**Closed by webbertakken** 2021-11-09 21:48 UTC
